[server]
host = "localhost" # http host
port = 8082        # http port
timeout = 30       # http timeout

[storage]
file = "db.sqlite" # database file
dir = "storage"    # files storage directory
size = 512         # max storage size (Mb)

[settings]
ttl = 604800           # max time to live (seconds) - 7 days
times = 100            # max times for users requests
size = 128             # max file size (Mb)
salt = "abc"           # additional key salt (replace it by a long random string for production)
gc = 10                # "garbage collector" timeout (seconds)
passlen = 15           # length for automatically created passwords
shutdown = 30          # shutdown server timeout (seconds)
